# Generated by Django 6.1 on 2026-08-30 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Farmer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100)),
                ('sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('address', models.TextField()),
                ('municipality', models.CharField(max_length=100)),
                ('contact_number', models.CharField(max_length=20)),
                ('date_added', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=10)),
                ('guarantor', models.CharField(max_length=200)),
                ('guarantor_contact', models.CharField(max_length=20)),
                ('approver', models.CharField(max_length=200)),
            ],
        ),
    ]
